### PR TITLE
additions and improvements

### PR DESCRIPTION
**Pull request by mertcangokgoz**
I made some changes
- Improved control mechanism for os type detection
- added regexp FQDN (against errors)

### CODE REVIEW

**Comment by ileri** [comment]
Firstly , thank you for your commit. You said that "Only works on Debian/Ubuntu and Centos/RHEL", but in my machine I'm using Fedora and it's working well.

**Comment by mertcangokgoz** [comment]
probably yes, but we haven't seen much on the server side

**Comment by ileri** [comment]
You are right , but it is still working on other distributions. Thanks for regex control, it is very good, but i think that , we should not restrict the os , what do you thinking?

**Comment by mertcangokgoz** [comment]
on some operating systems, may produce a different outcome, indexes can be mixed and need to restrict to reduce errors we don't want your users to get the error 

Just a suggestion ,the choice is yours :+1: 

good luck

**Comment by ileri** [comment]
In script we are already checking that "is apache directory exists", if our checked directories exists we can say that code will run untroubled.So i'm thinking that we dont need to restrict os "for NOW". 

Thanks for everything.

**Pull request merged**
